import { Car, CarStatus, FuelType, Prisma, PrismaClient, TransmissionType } from "@prisma/client";
import { DefaultArgs } from "@prisma/client/runtime/library";

const CARS: (Omit<Car,
    'baseDailyPrice' | 'baseWeeklyPrice' | 'baseMonthlyPrice' | 'chauffeurDailyPrice' | 'mileageLimit' | 'additionalMileage'
    | 'createdAt' | 'updatedAt' | 'deletedAt' | 'dealerId' | 'seo_title' | 'seo_description' | 'seo_keywords' | 'canonical'> & {
        baseDailyPrice: number,
        baseWeeklyPrice?: number,
        baseMonthlyPrice?: number
        chauffeurDailyPrice?: number
        mileageLimit?: number
        additionalMileage?: number
        images: string[]
    })[] = [
        {
            id: 'cmjuc3hnl000iobe2eak9vyy3',
            brandId: "cmk2p11cb0004830qt2vc0prl",
            categoryId: "cmk2p11fe000c830qpq2tcntu",
            name: "Mercedes-Benz G-Class",
            model: "G63 AMG",
            year: 2024,
            slug: "mercedes-benz-g63-amg-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 5,
            engineSize: "4.0L V8",
            horsepower: 577,
            topSpeed: 220,
            acceleration: 4.5,
            hasChauffeur: true,
            hasSelfDrive: true,
            baseDailyPrice: 2500,
            baseWeeklyPrice: 15000,
            baseMonthlyPrice: 55000,
            chauffeurDailyPrice: 3500,
            description: "Luxury SUV with exceptional off-road capabilities",
            highlights: ["4WD", "Premium Interior", "AMG Performance"],
            color: "Black",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 4,
            bags: 2,
            affordable: true,
            recommended: true,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: true,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "ABC-1234",
            vin: "ABC123456789",
            requirments: ["Must have a valid driver's license", "Must be at least 18 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hnl000iobe2eak9vyy3/1767206805134-o117m7ef4.jpg',
                '/uploads/cars/cmjuc3hnl000iobe2eak9vyy3/1767206805149-cu34oxfm93g.jpg',
                '/uploads/cars/cmjuc3hnl000iobe2eak9vyy3/1767206805158-gnagb0izqfr.jpg',
                '/uploads/cars/cmjuc3hnl000iobe2eak9vyy3/1767206805167-0r3onbordyw.jpg',
            ],
        },
        {
            id: 'cmjuc3hoh000kobe2sejwurce',
            brandId: "cmk2p11cu0005830q9dsvuepp",
            categoryId: "cmk2p11eq000b830qxi6cpir4",
            name: "BMW 7 Series",
            model: "740i",
            year: 2024,
            slug: "bmw-7-series-740i-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 5,
            engineSize: "3.0L I6",
            horsepower: 375,
            topSpeed: 250,
            acceleration: 5.1,
            hasChauffeur: true,
            hasSelfDrive: true,
            baseDailyPrice: 1800,
            baseWeeklyPrice: 11000,
            baseMonthlyPrice: 40000,
            chauffeurDailyPrice: 2800,
            description: "Flagship luxury sedan with cutting-edge technology",
            highlights: ["Executive Seating", "Advanced Tech", "Comfort Plus"],
            color: "White",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 4,
            bags: 2,
            affordable: true,
            recommended: true,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: true,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "ABC-2412",
            vin: "ABC123456719",
            requirments: ["Must have a valid driver's license", "Must be at least 18 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hoh000kobe2sejwurce/1767206835461-bh0g2oq23dt.jpg',
            ],
        },
        {
            id: 'cmjuc3hon000mobe26dyvbkc7',
            brandId: "cmk2p11dc0007830qb4pi0hfq",
            categoryId: "cmk2p11fl000d830q336hovs3",
            name: "Porsche 911",
            model: "Carrera S",
            year: 2024,
            slug: "porsche-911-carrera-s-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 4,
            engineSize: "3.0L Flat-6",
            horsepower: 450,
            topSpeed: 308,
            acceleration: 3.7,
            hasChauffeur: false,
            hasSelfDrive: true,
            baseDailyPrice: 3200,
            baseWeeklyPrice: 20000,
            baseMonthlyPrice: 75000,
            description: "Iconic sports car with legendary performance",
            highlights: ["Sports Mode", "Premium Sound", "Racing Heritage"],
            color: "Red",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 4,
            bags: 2,
            affordable: true,
            recommended: true,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: true,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "ABC-54312",
            vin: "ABC123456780",
            requirments: ["Must have a valid driver's license", "Must be at least 18 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hon000mobe26dyvbkc7/1767206824263-ip4hx3kvrv.jpg',
            ],
        },
        {
            id: 'cmjuc3hoz000pobe2lq8d9wz1',
            brandId: "cmk2p11cb0004830qt2vc0prl",
            categoryId: "cmk2p11fe000c830qpq2tcntu",
            name: "Range Rover",
            model: "Autobiography",
            year: 2024,
            slug: "range-rover-autobiography-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 5,
            engineSize: "4.4L V8",
            horsepower: 523,
            topSpeed: 250,
            acceleration: 4.6,
            hasChauffeur: true,
            hasSelfDrive: true,
            baseDailyPrice: 2300,
            baseWeeklyPrice: 14000,
            baseMonthlyPrice: 52000,
            chauffeurDailyPrice: 3300,
            description: "Ultra-luxury SUV combining comfort with all-terrain capability",
            highlights: ["Air Suspension", "Executive Rear Seats", "All-Terrain Drive"],
            color: "Silver",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 4,
            bags: 3,
            affordable: true,
            recommended: false,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: true,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "RR-2024",
            vin: "RR1234567890",
            requirments: ["Must have a valid driver's license", "Must be at least 21 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hoz000pobe2lq8d9wz1/image.png',
            ],
        },
        {
            id: 'cmjuc3hp4000robe2ab9xv1d2',
            brandId: "cmk2p11dc0007830qb4pi0hfq",
            categoryId: "cmk2p11gj000g830qyjyv0j6x",
            name: "Porsche 718",
            model: "Boxster GTS",
            year: 2024,
            slug: "porsche-718-boxster-gts-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 2,
            engineSize: "4.0L Flat-6",
            horsepower: 394,
            topSpeed: 288,
            acceleration: 4.0,
            hasChauffeur: false,
            hasSelfDrive: true,
            baseDailyPrice: 2800,
            baseWeeklyPrice: 17000,
            baseMonthlyPrice: 65000,
            description: "Open-top sports car delivering pure driving excitement",
            highlights: ["Convertible Roof", "Sport Chrono", "Mid-Engine Balance"],
            color: "Blue",
            mileageLimit: 200,
            additionalMileage: 15,
            oneDayRental: true,
            insurance: true,
            doors: 2,
            bags: 1,
            affordable: true,
            recommended: false,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: false,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "PX-718",
            vin: "PX718GTS2024",
            requirments: ["Must have a valid driver's license", "Must be at least 25 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hp4000robe2ab9xv1d2/image.png',
            ],
        },
        {
            id: 'cmjuc3hp9000tobe2c7z8m1k9',
            brandId: "cmk2p11cu0005830q9dsvuepp",
            categoryId: "cmk2p11eq000b830qxi6cpir4",
            name: "Mercedes-Benz S-Class",
            model: "S580",
            year: 2024,
            slug: "mercedes-benz-s580-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 5,
            engineSize: "4.0L V8",
            horsepower: 496,
            topSpeed: 250,
            acceleration: 4.4,
            hasChauffeur: true,
            hasSelfDrive: true,
            baseDailyPrice: 2000,
            baseWeeklyPrice: 12500,
            baseMonthlyPrice: 46000,
            chauffeurDailyPrice: 3000,
            description: "Flagship luxury sedan offering unmatched comfort and innovation",
            highlights: ["Massage Seats", "Ambient Lighting", "Advanced Driver Assist"],
            color: "Black",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 4,
            bags: 3,
            affordable: true,
            recommended: false,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: true,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "MB-S580",
            vin: "MBS5802024VIN",
            requirments: ["Must have a valid driver's license", "Must be at least 21 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hp9000tobe2c7z8m1k9/image.png',
            ],
        },
        {
            id: 'cmjuc3hpe000vobe2w4k9s8m3',
            brandId: "cmk2p11cu0005830q9dsvuepp",
            categoryId: "cmk2p11fl000d830q336hovs3",
            name: "Audi R8",
            model: "V10 Performance",
            year: 2023,
            slug: "audi-r8-v10-performance-2023",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 2,
            engineSize: "5.2L V10",
            horsepower: 602,
            topSpeed: 331,
            acceleration: 3.1,
            hasChauffeur: false,
            hasSelfDrive: true,
            baseDailyPrice: 3500,
            baseWeeklyPrice: 22000,
            baseMonthlyPrice: 82000,
            description: "Supercar performance with everyday drivability",
            highlights: ["Quattro AWD", "Carbon Ceramic Brakes", "V10 Engine"],
            color: "Grey",
            mileageLimit: 200,
            additionalMileage: 20,
            oneDayRental: true,
            insurance: true,
            doors: 2,
            bags: 1,
            affordable: true,
            recommended: true,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: false,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "R8-V10",
            vin: "AUDIR8V102023",
            requirments: ["Must have a valid driver's license", "Must be at least 25 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hpe000vobe2w4k9s8m3/image.png',
            ],
        },
        {
            id: 'cmjuc3hpk000xobe2r2m7f9q8',
            brandId: "cmk2p11dc0007830qb4pi0hfq",
            categoryId: "cmk2p11gf000f830qblfykbdj",
            name: "BMW M4",
            model: "Competition",
            year: 2024,
            slug: "bmw-m4-competition-2024",
            transmission: TransmissionType.AUTOMATIC,
            fuelType: FuelType.PETROL,
            seats: 4,
            engineSize: "3.0L I6 Twin-Turbo",
            horsepower: 503,
            topSpeed: 290,
            acceleration: 3.9,
            hasChauffeur: false,
            hasSelfDrive: true,
            baseDailyPrice: 2100,
            baseWeeklyPrice: 13000,
            baseMonthlyPrice: 48000,
            description: "High-performance coupe blending power with precision handling",
            highlights: ["M Sport Exhaust", "Adaptive Suspension", "Track Mode"],
            color: "Yellow",
            mileageLimit: 250,
            additionalMileage: 10,
            oneDayRental: true,
            insurance: true,
            doors: 2,
            bags: 2,
            affordable: true,
            recommended: false,
            hasBackupCamera: true,
            hasBluetooth: true,
            hasSunroof: false,
            hasLeatherSeats: true,
            hasGPS: true,
            licensePlate: "BMW-M4",
            vin: "BMWM42024VIN",
            requirments: ["Must have a valid driver's license", "Must be at least 23 years old"],
            status: CarStatus.ACTIVE,
            images: [
                '/uploads/cars/cmjuc3hpk000xobe2r2m7f9q8/image.png',
            ],
        },
    ]

const faqs = [
    {
        question: "How do I rent a car through " + process.env.NEXT_PUBLIC_SITE_NAME + "?",
        answer:
            "Browse our selection of cars, select your preferred vehicle, choose rental dates, and contact the dealer directly via call or WhatsApp.",
    },
    {
        question: "What documents do I need to rent a car?",
        answer:
            "You'll need a valid driver's license, passport or Emirates ID, and a credit card for the security deposit.",
    },
    {
        question: "Is insurance included in the rental price?",
        answer:
            "Basic insurance is included in all our rental packages. Additional coverage options are available at checkout.",
    },
]

export async function createCars(prisma: PrismaClient<Prisma.PrismaClientOptions, never, DefaultArgs>) {
    for (const car of CARS) {
        const images = car.images
        // @ts-expect-error remove images from car
        delete car.images

        await prisma.car.create({
            data: {
                ...car,
                images: {
                    createMany: {
                        data: images.map(image => ({ url: image }))
                    }
                },
                carFaqs: {
                    createMany: {
                        data: faqs
                    }
                },
            }
        });
    }

    console.log(`✅ Created ${CARS.length} sample cars`);
}
